language: ruby
cache: bundler

rvm:
  - 2.1
  - 2.2

env:
  - DB=postgresql

script:
  - RAILS_ENV=test rake db:create
  - RAILS_ENV=test bundle exec rake --trace db:migrate
  - bundle exec rake db:test:prepare
  - bundle exec rake

addons:
  postgresql: "9.3"
